apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: kubernetes-yardinternet-nl
spec:
  secretName: kubernetes-yardinternet-nl-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetes.yardinternet.nl
  dnsNames:
    - kubernetes.yardinternet.nl
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kubernetes.yardinternet.nl